services:
  gametimarr:
    image: plexeum/gametimarr:latest
    container_name: gametimarr
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - DB_PATH=/data/gametimarr.db
      - DOWNLOAD_PATH=/downloads
      - DESTINATION_PATH=/watch
      - LOG_PATH=/logs
      - WEB_PORT=7667
    volumes:
      - ./data:/data
      - ./logs:/logs
      - qbit_downloads:/downloads
      - sports_library:/watch
    ports:
      - "7667:7667"

volumes:
  qbit_downloads:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.0.65/UtorrentCloud2/qBit Files - Cloud 2"
      o: "username=guest,password=,vers=2.1,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"

  sports_library:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.0.77/i/ChannelsDVR/Imports/TV/Sports"
      o: "username=guest,password=,vers=2.1,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"